version: 2.1

jobs:
  build:
    docker:
      - image: python:3.8

    working_directory: ~/python-app

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt

      - run:
          name: Run tests
          command: |
            python -m unittest discover -s tests/

      - run:
          name: Run application
          command: |
            python app.py

workflows:
  version: 2
  build:
    jobs:
      - build

