version: 2.1

jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 main.py
  test:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 main-test.py
      - image: cimg/python:3.8

    working_directory: ~/python-app

    steps:
      - checkout

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
